name: 'Run Python in Venv'
description: 'Create a new Python Venv with specified dependecies and run commands'
author: 'Samuel Quesne'

inputs:
  python-version:
    description: 'Python version'
    required: true
  requirement-file:
    description: 'Path to the pip requirements file'
    required: false
  constraints-file:
    description: 'Path to the pip package contraints file'
    required: false
  requirements:
    description: 'Package version to be installed in the venv'
    required: false
  constraints:
    description: 'Constraints on individual package versions'
    required: false
  run:
    description: 'Shell commands to run after setup'
    required: true


runs:
  using: 'composite'
  steps:
    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: 'Setup Venv'
      shell: bash
      run: python -m venv venv

    - name: 'Install Dependecies from Requirements file'
      if: "${{ inputs.requirements-file != '' }}"
      shell: bash
      run: |
        source venv/bin/activate
        pip install -q -c ${{ inputs.constraints-file }}
        touch /tmp/constraints.txt
        echo '${{ inputs.constraints }}' > /tmp/constraints.txt
        pip install -q -c /tmp/constraints.txt
        pip install -r ${{ inputs.requirements-file }}
        deactivate

    - name: 'Install Dependecies'
      if: "${{ inputs.requirements != ''}}"
      shell: bash
      run: |
        source venv/bin/activate
        pip install -q -c ${{ inputs.constraints-file }}
        touch /tmp/constraints.txt
        echo '${{ inputs.constraints }}' > /tmp/constraints.txt
        pip install -q -c /tmp/constraints.txt
        pip install ${{ inputs.requirements }}
        deactivate

    - name: 'Run Shell commands with Venv'
      shell: bash
      run: |
        source venv/bin/activate
        ${{ inputs.run }}
        deactivate
