name: 'Run Python in Venv'
description: 'Create a new Python Venv with specified dependecies and run commands'
author: 'Samuel Quesne'

inputs:
  python-version:
    description: 'Python version'
    required: true
  requirement-file:
    description: 'Path to the pip requirements file'
    required: false
  constraints-file:
    description: 'Path to the pip package contraints file'
    required: false
  requirements:
    description: 'Package version to be installed in the venv'
    required: false
  contraints:
    description: 'Constraints on individual package versions'
    required: false
  run:
    description: 'Shell commands to run after setup'
    required: true


runs:
  using: 'composite'
  steps:
    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: 'Setup Venv'
      run: python -m venv venv

    - name: 'Install Dependencies'
      run: |
        source venv/bin/activate
        pip install -r ${{ inputs.requirements-file }}
        pip install -c ${{ inputs.constraints-file }}
        pip install ${{ inputs.requirements }}
        pip install ${{ inputs.constraints }}
        deactivate
    - name: 'Run Shell commands with Venv'
      run: |
        source venv/bin/activate
        ${{ inputs.run }}
        deactivate
