name: 'Update Checkbox on PR Merge'

on:
  pull_request:
    types:
      - closed

jobs:
  update-checkbox:
    runs-on: ubuntu-22.04

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Setup Python'
        uses: ./.github/actions/run-python-venv
        env:
          REPO_NAME: "${{ github.repository }}"
          PR_NUMBER: "${{ github.event.number }}"
        with:
          python-version: '3.10'
          requirements: 'PyGithub==1.58'
          run: python .github/scripts/update-checkbox.py
